CREATE TABLE IF NOT EXISTS IDN_REGISTERED_DEVICE (
    ID              CHAR(36)      NOT NULL,
    USER_ID         VARCHAR(255)  NOT NULL,
    DEVICE_NAME     VARCHAR(255)  NOT NULL,
    DEVICE_MODEL    VARCHAR(255),
    DEVICE_OS       VARCHAR(100),
    DEVICE_TYPE     VARCHAR(50)   NOT NULL,
    PUBLIC_KEY      VARCHAR(4096) NOT NULL,
    CHALLENGE_USED  VARCHAR(512)  NOT NULL,
    STATUS          VARCHAR(20)   NOT NULL DEFAULT 'ACTIVE',
    REGISTERED_AT   TIMESTAMP     NOT NULL,
    LAST_USED_AT    TIMESTAMP     NULL,
    METADATA        VARCHAR(4096) NULL,
    TENANT_ID       INTEGER       NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE (USER_ID, PUBLIC_KEY)
);

CREATE INDEX IF NOT EXISTS IDX_IRD_USER_TENANT ON IDN_REGISTERED_DEVICE (USER_ID, TENANT_ID);
CREATE INDEX IF NOT EXISTS IDX_IRD_STATUS ON IDN_REGISTERED_DEVICE (STATUS, TENANT_ID);

