CREATE TABLE IF NOT EXISTS IDN_DEVICE_POLICY (
    ID          INTEGER       NOT NULL AUTO_INCREMENT,
    POLICY_ID   CHAR(36)      NOT NULL,
    POLICY_NAME VARCHAR(255)  NOT NULL,
    RULE_ID     CHAR(36),
    TENANT_ID   INTEGER       NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE (POLICY_ID),
    UNIQUE (POLICY_NAME, TENANT_ID)
);
